#
#  Copyright (c) 2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#

---
name: "Publish Snapshot Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  secrets-presence:
    name: "Check for required credentials"
    runs-on: ubuntu-latest
    outputs:
      HAS_OSSRH: ${{ steps.secret-presence.outputs.HAS_OSSRH }}
    steps:
      - name: Check whether secrets exist
        id: secret-presence
        run: |
          [ ! -z "${{ secrets.GPG_PASSPHRASE }}" ] &&
          [ ! -z "${{ secrets.GPG_PRIVATE_KEY }}" ] &&
          [ ! -z "${{ secrets.OSSRH_PASSWORD }}" ] &&
          [ ! -z "${{ secrets.OSSRH_USERNAME }}" ] && echo "HAS_OSSRH=true" >> $GITHUB_OUTPUT
          exit 0

  Publish-Snapshot:
    name: "Publish artefacts to OSSRH Snapshots"
    runs-on: ubuntu-latest
    needs: [ secrets-presence ]
    if: |
      needs.secrets-presence.outputs.HAS_OSSRH
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-maven-artifacts
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          osshr-username: ${{ secrets.OSSRH_USERNAME }}
          osshr-password: ${{ secrets.OSSRH_PASSWORD }}
