name: publish dependencies

on:
  workflow_call:

jobs:
  publish-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-dataspacetck/tck-common/.github/actions/generate-dependencies-file@main

      - name: prepare deploy
        run: |
          mkdir public
          mv DEPENDENCIES public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          keep_files: true
