#
#  Copyright (c) 2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#

---
name: "Publish Snapshot Build"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  secrets-presence:
    name: "Check for required credentials"
    runs-on: ubuntu-latest
    outputs:
      HAS_CREDENTIALS: ${{ steps.secret-presence.outputs.HAS_CREDENTIALS }}
    steps:
      - name: Check whether secrets exist
        id: secret-presence
        run: |
          [ ! -z "${{ secrets.GPG_PASSPHRASE }}" ] &&
          [ ! -z "${{ secrets.GPG_PRIVATE_KEY }}" ] &&
          [ ! -z "${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}" ] &&
          [ ! -z "${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}" ] && echo "HAS_CREDENTIALS=true" >> $GITHUB_OUTPUT
          exit 0

  Publish-Snapshot:
    name: "Publish artefacts to Maven Central Snapshots"
    runs-on: ubuntu-latest
    needs: [ secrets-presence ]
    if: |
      needs.secrets-presence.outputs.HAS_CREDENTIALS
    steps:
      - uses: actions/checkout@v5
      - uses: eclipse-dataspacetck/tck-common/.github/actions/publish-maven-artifacts@main
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          maven-username: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          maven-password: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
