#
#  Copyright (c) 2024 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
#
#  This program and the accompanying materials are made available under the
#  terms of the Apache License, Version 2.0 which is available at
#    https://www.apache.org/licenses/LICENSE-2.0
#
#  SPDX-License-Identifier: Apache-2.0
#
#  Contributors:
#    Bayerische Motoren Werke Aktiengesellschaft (BMW AG) - initial API and implementation
#

---
name: Trigger (finalize) Release

on:
  workflow_dispatch:

jobs:
  Release:
    uses: eclipse-dataspacetck/tck-common/.github/workflows/tck-release.yml@main
    permissions:
      contents: write
    secrets: inherit
