name: "Publish Snapshot Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  secrets-presence:
    name: "Check for required credentials"
    runs-on: ubuntu-latest
    outputs:
      HAS_OSSRH: ${{ steps.secret-presence.outputs.HAS_OSSRH }}
    steps:
      - name: Check whether secrets exist
        id: secret-presence
        run: |
          [ ! -z "${{ secrets.ORG_GPG_PASSPHRASE }}" ] &&
          [ ! -z "${{ secrets.ORG_GPG_PRIVATE_KEY }}" ] &&
          [ ! -z "${{ secrets.ORG_OSSRH_USERNAME }}" ] && echo "HAS_OSSRH=true" >> $GITHUB_OUTPUT
          exit 0

  Publish-Snapshot:
    name: "Publish artefacts to OSSRH Snapshots"
    runs-on: ubuntu-latest
    needs: [ secrets-presence ]
    if: |
      needs.secrets-presence.outputs.HAS_OSSRH
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/publish-maven-artifacts
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          osshr-username: ${{ secrets.OSSRH_USERNAME }}
          osshr-password: ${{ secrets.OSSRH_PASSWORD }}


## todo: decide how DEPENDENCIES is going to be hosted
#  Publish-Dependencies:
#    uses: ./.github/workflows/publish-dependencies.yml@main
#    secrets: inherit